In [ ]:
import pandas as pd

In [4]:
df= pd.read_csv("fruits_data.csv")
df

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
0,01-01-2022,230.0,46.0,65.0,184.0,NaN
1,01-02-2022,237.0,50.0,72.0,173.0,72.0
2,01-03-2022,259.0,NaN,NaN,NaN,93.0
3,01-04-2022,NaN,41.0,75.0,175.0,74.0
4,01-05-2022,240.0,48.0,NaN,185.0,84.0
5,01-06-2022,234.0,45.0,66.0,194.0,93.0
6,01-07-2022,NaN,NaN,70.0,174.0,NaN
7,01-08-2022,236.0,46.0,66.0,187.0,86.0
8,01-09-2022,232.0,41.0,71.0,NaN,93.0
9,01-10-2022,240.0,48.0,NaN,198.0,97.0

In [6]:
print(df.shape)

(10, 6)

In [9]:
print(df.columns)

Index(['date', 'apple(1kg)', 'banana(1 dozen)', 'grapes(1kg)', 'mango(1kg)',
       'Water Melons(1)'],
      dtype='object')

In [8]:
df

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
0,01-01-2022,230.0,46.0,65.0,184.0,NaN
1,01-02-2022,237.0,50.0,72.0,173.0,72.0
2,01-03-2022,259.0,NaN,NaN,NaN,93.0
3,01-04-2022,NaN,41.0,75.0,175.0,74.0
4,01-05-2022,240.0,48.0,NaN,185.0,84.0
5,01-06-2022,234.0,45.0,66.0,194.0,93.0
6,01-07-2022,NaN,NaN,70.0,174.0,NaN
7,01-08-2022,236.0,46.0,66.0,187.0,86.0
8,01-09-2022,232.0,41.0,71.0,NaN,93.0
9,01-10-2022,240.0,48.0,NaN,198.0,97.0

In [10]:
new_df = df.fillna('-1')

In [11]:
new_df

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
0,01-01-2022,230.0,46.0,65.0,184.0,-1
1,01-02-2022,237.0,50.0,72.0,173.0,72.0
2,01-03-2022,259.0,-1,-1,-1,93.0
3,01-04-2022,-1,41.0,75.0,175.0,74.0
4,01-05-2022,240.0,48.0,-1,185.0,84.0
5,01-06-2022,234.0,45.0,66.0,194.0,93.0
6,01-07-2022,-1,-1,70.0,174.0,-1
7,01-08-2022,236.0,46.0,66.0,187.0,86.0
8,01-09-2022,232.0,41.0,71.0,-1,93.0
9,01-10-2022,240.0,48.0,-1,198.0,97.0

In [14]:
new_df = df.fillna({
     'banana(1 dozen)': df['banana(1 dozen)'].mean(),
        'grapes(1kg)': df['grapes(1kg)'].median(),
        'mango(1kg)': df['mango(1kg)'].median(),
        'Water Melons(1)': "Not Available",
        
    })

In [15]:
new_df

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
0,01-01-2022,230.0,46.000,65.0,184.0,Not Available
1,01-02-2022,237.0,50.000,72.0,173.0,72.0
2,01-03-2022,259.0,45.625,70.0,184.5,93.0
3,01-04-2022,NaN,41.000,75.0,175.0,74.0
4,01-05-2022,240.0,48.000,70.0,185.0,84.0
5,01-06-2022,234.0,45.000,66.0,194.0,93.0
6,01-07-2022,NaN,45.625,70.0,174.0,Not Available
7,01-08-2022,236.0,46.000,66.0,187.0,86.0
8,01-09-2022,232.0,41.000,71.0,184.5,93.0
9,01-10-2022,240.0,48.000,70.0,198.0,97.0

In [ ]:
new_df = df.fillna(method = "ffill")

In [ ]:
new_df

In [ ]:
#write the code here
new_df = df.dropna(thresh=4)

#show the dataframe 'new_df'
new_df

In [ ]:
#write the code here
new_df = df.dropna()


#show the dataframe 'new_df'
new_df

In [ ]:
#save the dataframe to 'final_data.csv'
new_df.to_csv('final_data.csv', index = False)